name: Update GAIA PLATFORMS Structure

on:
  # Run on schedule (weekly)
  schedule:
    - cron: '0 0 * * 0'  # Runs at midnight on Sunday
  
  # Run when changes are pushed to specific directories
  push:
    paths:
      - 'GAIA-AIRs/**'
      - 'GAIA-SPACEs/**'
      - 'GAIA-GREEN-TECHNOLOGIES/**'
      - 'SharedServices/**'
      - 'GP-FD/**'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      full_rebuild:
        description: 'Perform full structure rebuild'
        required: false
        default: 'false'
      update_version:
        description: 'Update VERSION.md files'
        required: false
        default: 'false'

jobs:
  update-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jsonschema gitpython

      - name: Run structure validation and update
        run: python .github/scripts/update_structure.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FULL_REBUILD: ${{ github.event.inputs.full_rebuild || 'false' }}
          UPDATE_VERSION: ${{ github.event.inputs.update_version || 'false' }}

      - name: Commit changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "Auto-update GAIA PLATFORMS structure [skip ci]"
          git push
